// This file is automatically generated by Firebase Studio.
// Do not edit this file manually, as your changes will be overwritten.

// Your web app's Firebase configuration
// For Firebase JS SDK v7.20.0 and later, measurementId is optional
export const firebaseConfig = {
  "projectId": "studio-4210702598-6f2b7",
  "appId": "1:503376226205:web:e222051c532150600d7174",
  "apiKey": "AIzaSyAizop6_gONjkZAQTzD4nEqtzLj6vINVsI",
  "authDomain": "studio-4210702598-6f2b7.firebaseapp.com",
  "measurementId": "",
  "messagingSenderId": "503376226205"
};
